INSERT INTO "SYSTEM"."DOCTORS" (ID, CODE, CONSULTING_ROOM, DOMICILE, SPECIALTY, YEARS) VALUES ('1', 'A1g5', 'a203', '1', 'cirujano', '4');
INSERT INTO "SYSTEM"."PATIENTS" (ID, BIRTHDAY, FEE, IDENTIFICATION, LAST_NAME, NAME, TREATMENT) VALUES ('1', '10-10-1995', '1000', 'a11515', 'Insuasty', 'Andres', '1');
INSERT INTO "SYSTEM"."CITAS" (PACIENT_ID, DOCTOR_ID, ID, NEW_DATE, TIME) VALUES ('1', '1', '1', '09-09-2019', '14:00');

